### ISSUE TITLE
assigned_terms and assigned_posts not working properly in site_reviews_summary

### ISSUE THREAD

**Issue by jnasoy** [pryley/site-reviews#15]
Hello,

I want to display rate summary of a certain category of a certain post. I have the following code

```php
<?php echo do_shortcode('[site_reviews_summary assigned_posts="post_id" assigned_terms="overall" text="({num})" hide="bars,title,author" class="service-rating-display"]')?>
```

But this code doesn't work properly. It will display the average rating of all category (i have 4 categories in total) in that certain post + the "overall" ratings of  other post.

![image](https://user-images.githubusercontent.com/7227288/97165815-40e6ec00-17bf-11eb-874a-6cee3ef8f3d5.png)
![image](https://user-images.githubusercontent.com/7227288/97166811-d171fc00-17c0-11eb-983b-559956ac5385.png)

But the display in a post that don't have rating yet, it will show an average rating of all overall rating of other posts

![image](https://user-images.githubusercontent.com/7227288/97167004-139b3d80-17c1-11eb-9adf-96ff00c427f9.png)

I've already tried the built in tools and I even had clean reinstall of the plugin, but the issue still persist.

Seems to work properly if no assigned_terms set

My setup:
* Latest version of the plugin
* Local by Flywheel
* Windows 10

Thank you

**Comment by pryley** [comment]
This is working as designed.

a. If this is your shortcode and you are limiting review submissions:

`[site_reviews_summary assigned_posts=post_id assigned_terms=overall]`

b. And if these are your reviews:

![](https://user-images.githubusercontent.com/7227288/97166811-d171fc00-17c0-11eb-983b-559956ac5385.png)

c. And if the current assign page is "Beetbox by Turnip The Beet"
 
Then Site Reviews will calculate the average rating for all reviews that are assigned to the  "Beetbox by Turnip The Beet" **and** the "overall" category.

According to the screenshot, that means two reviews: a 1 star review and a 4 star review. The average rating of these is 2.5 stars (total rating sum of 5 divided by 2 reviews).

**Comment by pryley** [comment]
This is working as designed.

The default behaviour when using restricting reviews to assigned posts or categories is loose comparison instead of strict comparison (i.e. the SQL query uses OR instead of AND).

This is different from the review limits restriction setting which uses strict comparison (i.e. AND instead of OR).

For example, if you are assigning a review to multiple posts:

`[site_reviews_form assigned_posts=1,2]`

Then `[site_reviews assigned_posts=1,2]` and `[site_reviews_summary assigned_posts=1,2]` will display all reviews that have been assigned to post with and ID of 1 **OR** 2.

The same goes for assigned categories.`[site_reviews assigned_terms=house,apartment]` and `[site_reviews_summary assigned_terms=house,apartment]` will display all reviews that have been assigned to the "house" category **OR** the "apartment" category.

The same goes for assigned posts and categories.`[site_reviews assigned_posts=1 assigned_terms=house,apartment]` and `[site_reviews_summary assigned_posts=1 assigned_terms=house,apartment]` will display all reviews that have been assigned to the "house" category **OR** the "apartment" category, **OR** the post with an ID of 1.

If you prefer strict comparison, you can use the `site-reviews/query/sql/clause/operator` filter hook to change it:

```php
add_filter('site-reviews/query/sql/clause/operator', function () {
    return 'AND';
});
```

This will change `[site_reviews assigned_posts=1 assigned_terms=house,apartment]` and `[site_reviews_summary assigned_posts=1 assigned_terms=house,apartment]` to: Display all reviews that have been assigned to the "house" category **AND** the "apartment" category, **AND** the post with an ID of 1.

**Comment by jnasoy** [comment]
Thank you for response Paul.


  *   There's no setup limit yet for the submission
  *   The 2.5 star review is shown in "Pastry Base", which doesn't have review yet so it should be zero.
  *   The "Beetbox by Turnip The Beet" shows 2.2 star with 5 count review entry, which is not correct.
  *   Why does the plugin will be going to include other categories in the computation if I'm only limiting it in overall category by passing assigned_terms="overall".
  *   Why does the plugin will be going to include other rate assigned to other post in the computation if I'm only limiting it in the current post by passing assigned_posts="post_id".
  *   Let's take the scenario you've provided as an example, if I have the following shortcode [site_reviews_summary assigned_posts="post_id" assigned_terms="overall"] in "Beetbox by Turnip The Beet" page, the plugin should only calculate the average of all rating in "overall" category that are assigned to "Beetbox by Turnip The Beet". The page should display 4 star with a count of 1 not 2.2 with count of 5 since I only have one review with overall category that was assigned to the said page.
  *   This logic way working in older version of the plugin with the shortcode [site_reviews_summary assigned_to="post_id" category="overall"]



//JNB ✌️
________________________________

**Comment by pryley** [comment]
Please see my updated response and ignore the previous one.

**Comment by jnasoy** [comment]
Thank you so much for the detailed response.

I've tried applying the filters you've suggest but it still doesn't work, seems like it still using **OR**

here's my full shortcode
```php
<?php echo do_shortcode('[site_reviews_summary assigned_posts="post_id" assigned_terms="overall" text="({num})" hide="bars,title,author" class="service-rating-display"]')?>
```
and have this in my functions.php
```php
apply_filters('site-reviews/query/sql/clause/operator', function () { return 'AND'; });
```
![image](https://user-images.githubusercontent.com/7227288/97214299-e28d2e00-17fd-11eb-8f28-932dce78c67f.png)
![image](https://user-images.githubusercontent.com/7227288/97214549-39930300-17fe-11eb-878d-440f08e6d21e.png)

**Comment by pryley** [comment]
It should actually be this:

```php
add_filter('site-reviews/query/sql/clause/operator', function () {
    return 'AND';
});
```

**Comment by pryley** [comment]
FYI: The next minor version update will include this setting:

![image](https://user-images.githubusercontent.com/134939/97219566-cce11f80-178f-11eb-8f12-4f69af0ab7f2.png)

**Comment by jnasoy** [comment]
Nice, it seems working now. Thank you
