### ISSUE TITLE
Tag v5.0.1 just vanished

### ISSUE THREAD

**Issue by szepeviktor** [pryley/site-reviews#22]
It was the recommended way to write plugins for WordPress.
https://github.com/szepeviktor/phpstan-wordpress/commit/556275d21de761c799fe3292098bce0e2a040812

Now that tag is gone.
What has happened?

**Comment by szepeviktor** [comment]
BTW Come and see my ongoing research on plugin main file parts: https://github.com/szepeviktor/small-project/blob/master/MAIN-FILE-PARTS.md
There is a sample implementation included.

**Comment by pryley** [comment]
The v5.0.0 release was a big one due to the introduction of custom database tables. However, v5.0.0-5.1.0 did not support multisite so v5.2.0 [was released quickly](https://github.com/pryley/site-reviews/blob/5e727b31cbcf059fbf521d1a0c9a9fb06836b0d8/readme.txt#L116-L130) to fix this.

Because of the problems it introduced on multisite installs, I pulled the v5.0.x-5.1.x tags immediately as some people use https://wpackagist.org (i.e. https://roots.io/bedrock/).

If you would like to link to Site Reviews, I would change it to any tag after 5.2.0, or simply link to the master branch.

**Comment by szepeviktor** [comment]
Thank you for the explanation!

> If you would like to link to Site Reviews

I encourage you too to use namespaced functions, modern OOP technology and leave the PHP4-rooted WordPress approach behind.

**Comment by szepeviktor** [comment]
I must admit there are a lot of things to learn from in this plugin.

**Comment by pryley** [comment]
That will all come in version 6.

The plugin has 20k+ active users and adoption of PHP 7+ is slower in the WordPress community. As much as I would like to use strict typing and all the modern features of PHP 7+, I can't release a minor version of the plugin that will cause it to deactivate for many users.

Version 5 brought a lot of changes and bumped the minimum WordPress version to 5.5 which is an easy upgrade for most people.  Version 6 will bump the minimum PHP version, and enough time should have passed to not make it as big of a deal.

**Comment by szepeviktor** [comment]
> adoption of PHP 7+ is slower in the WordPress community

Do people say _slower_ for 80% adaptation? :) https://wordpress.org/about/stats/#php_versions

**Comment by pryley** [comment]
Well...I'd say that is in comparison to other PHP communities.

It may be a small percentage, but that percentage I would have to provide support for when the plugin stops working and deactivates on their website. Choose your battles! 🙂

**Comment by pryley** [comment]
Also, the plugin was first released before WordPress performed PHP version checking, so I left the activation logic as is for now. A few other things I'm not happy with is the naming structure, for example, "Modules" is misleading as those classes are not modular. Version 6 will change a few things in how the plugin is structured.
