### ISSUE TITLE
Feature request: Lazy load

### ISSUE THREAD

**Issue by wpsumo** [pryley/site-reviews#7]
@pryley
What do you think about this?

How about lazy loading the whole widget. If they are used below the fold especially at the end of the page it could really benefit to lazy load everything.

Options for users:
No lazy load
Lazy load on scroll (specify off-set)
Lazy load on "load reviews click"

Lay load options to select if everything should be lazy-loaded or just one or another widget should etc.

It would improve performance and rendering (TTFB, FCP, and FMP) as the browser won't render and calculate the doc as the divs and images and style + js aren't loaded until it's used and needed. As it's not a part of the DOM until it's needed.

**Comment by pryley** [comment]
Site Reviews does not load in an iframe, it is part of the HTML of your webpage. 

Please show an example online that demonstrates the _performance benefit_ and method of lazy loading html content (not images) of a page.

**Comment by wpsumo** [comment]
Sure: https://www.sertmedia.com/lazy-load-your-wordpress-comments-for-better-performance/

Would be great to have this integrated into site reviews, so no matter way adding it, Gutenberg shortcodes etc it can be lazy loaded.

Options for users:
No lazy load
Lazy load on scroll (specify off-set)
Lazy load on "load reviews click"
Lazy load after page fully rendered.

**Comment by pryley** [comment]
The problem with this is that it is not SEO friendly. You generally want your reviews accessible to search engines, and if using the schema options on the [site_reviews] shortcode, the added Review schema requires that the reviews are visible to search engines.

Another concern is user experience. The few milliseconds you save by lazy loading reviews may make the site experience worse for your visitors as lazy-loading requires an AJAX request on scroll which can make your site jump as the content loads.

Lazy loading your posts used to be very popular a few years ago, but many stay away from it now because of the SEO and user experience implications. Reviews should not be classified the same as comments; they hold a very different purpose and are more important and relevant to your customers. If your site is loading slow, the culprit will likely not be due to the ~0.2ms of time it takes to load the reviews...

If you want to optimise the review loading and you have enabled avatars, I recommend that you:

1. Install a lazy loading plugin for images
2. Only display up to 10 reviews
3. Use the pagination option with ajax
4. If you are assigning reviews, only assign to either a category or a post ID, not both

However, I will add this request to the Roadmap for future consideration and review, though I cannot promise that it will ever be implemented. Likely, the only lazy loading that will be added will be for the avatars.
