### ISSUE TITLE
Summary recalculation problem

### ISSUE THREAD

**Issue by bkmediagroup-josh** [pryley/site-reviews#8]
I'm having an issue where summaries that include multiple categories and summaries that only include one category aren't recalculating properly. When using the recalculate button under tools, it seems to toggle between one being correct and the other being correct. I recorded a screencast that demonstrates this behavior.

https://youtu.be/dF2a9Ts5Qm8

**Comment by pryley** [comment]
Hi Josh,

_This github repository is only for development, support issues are not handled here._

However, since you took some effort to create a video, I'll respond here.

1. The first thing is that Site Reviews does not actually support assigning reviews to multiple categories (since v3.0). The reason is that summary calculations are tracked and cached instead of being recalculated on every page load, and dealing with multiple assignments and the flexibility of combinations that the shortcodes provide makes it unwieldy to manage well. You may also notice if you edit a review that only one category in the list can be selected at a time. This is why.

If you are using the shortcodes with multiple category IDs (even in the summary), in reality, only the first one will be used and there may be unintended side-effects in the way it works.

Site Reviews allows you to assign reviews to a post ID or/and a category, so a workaround for this is to assign reviews directly to your product pages, and optionally, also to a category if more flexibility is needed (although for performance reasons, I recommend sticking to one or the other).

Here is an example:

**On a tent product page:**

```
[site_reviews_summary assigned_to=post_id category=tent]

[site_reviews assigned_to=post_id category=tent display=10 pagination=ajax]

[site_reviews_form assign_to=post_id category=tent]
```

**On an accessory product page:**

```
[site_reviews_summary assigned_to=post_id category=accessory]

[site_reviews assigned_to=post_id category=accessory display=10 pagination=ajax]

[site_reviews_form assign_to=post_id category=accessory]
```

When it comes to assigning reviews, rule of thumb is that if you are assigning to something that has its own permalink and Post ID (i.e. page, post, product, event, etc.), then assign to its Post ID; if it does not have a permalink, create a category for it and assign to the category.

_Site Reviews v5.0 (which is currently in development) will allow you to assign reviews to multiple categories, multiple Post IDs, and multiple users. There is no release date yet for v5.0._

2. It sounds like you may not be using the latest version of Site Reviews. There was an issue related to categories that was fixed in a recent update where on some server configurations, the database queries triggered when recalculating summary ratings for categories were not being performed synchronously (one after the other in order).  

Please make sure that you are using the latest version of Site Reviews. For more information, please see: https://wordpress.org/support/topic/plugin-suddenly-broken/#post-12675206

I am going to close this issue now. In future, please use the [WordPress forum](https://wordpress.org/support/plugin/site-reviews/) for any future support requests you may have.
